# Generated by Django 5.0.2 on 2024-02-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ends_in',
            field=models.DateField(),
        ),
    ]
